### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by DIRIKtv** [Borisizdabezt/exitlag-trial-activator#2]
I tried it this morning and it showed 3 VIP days on the Exitlag application but I came back a couple of hours later and opened it up and it said 0 VIP days.

**Comment by Borisizdabezt** [comment]
it's not patched bro, maybe you entered wrong password

**Comment by Borisizdabezt** [comment]
you need to enter your exitlag's password to this script activate your account

**Comment by Borisizdabezt** [comment]
![image](https://user-images.githubusercontent.com/90611639/139520059-3c4c573e-9a02-4848-924f-c6c526c4b18e.png)
if it shows like mine, it will be activated

**Comment by DIRIKtv** [comment]
Check out this issue that I posted on Gatolouco's exitlag activator - https://github.com/gato-louco/exitlag-account-activator/issues/26. When I run the script it goes to 3 VIP days but then I log into the exitlag application and it goes back to 0 days. This same thing happens with yours. I have tried with 3 different accounts.

**Comment by DIRIKtv** [comment]
So when I log into the exitlag application it works and says 3 days but once I close the program and reopen it, it goes back to 0 days.

**Comment by DIRIKtv** [comment]
Ok idk what I did but it works rn. I am also allowed to reopen the program with the 3 days still staying

**Comment by Borisizdabezt** [comment]
run setup.exe with administrator?

**Comment by Borisizdabezt** [comment]
yea it's patched, i will fix it in next version

**Comment by itsOwen** [comment]
> yea it's patched, i will fix it in next version

u will fix it lol u just copy pasted the whole code

**Comment by Borisizdabezt** [comment]
nah, i will make it more easily for those who are new to python :(

**Comment by itsOwen** [comment]
> nah, i will make it more easily for those who are new to python :(

so the new version u posted works?

**Comment by Borisizdabezt** [comment]
MOVE MOVE MOVE!
https://github.com/Borisizdabezt/exitlag-hwid-spoofer
