### ISSUE TITLE
After logging in, it will be 0 day later

### ISSUE THREAD

**Issue by Borisizdabezt** [Borisizdabezt/exitlag-trial-activator#3]
men i think we need to change our hwid and restart PC

**Comment by Borisizdabezt** [comment]
it shows 0 day in exitlag website but still working lul (only working if you don't restart ur PC and log out exitlag)

**Comment by gosu821** [comment]
Ý hay đấy nhưng tôi chưa hiểu ở chỗ cái hwid ý, thì sao không random hwid rồi gửi tới bên exitlag

**Comment by Borisizdabezt** [comment]
exitlag trial activator nó sẽ random hwid gửi đến bọn exitlag, bọn exitlag sẽ cho 3 ngày nhưng hwid của mình đã từng nhận 3 ngày nên nó sẽ reset thành 0 ngày

**Comment by Borisizdabezt** [comment]
mình làm nó ngẫu nhiên thì phải restart nữa

**Comment by Borisizdabezt** [comment]
mà giờ nó đã update sau vài phút nó check thì nó tự động tắt luôn :(( 
chắc downgrade xuống 4.198 quá

**Comment by Borisizdabezt** [comment]
ở bản 4.198 thì vẫn dùng ngon ăn

**Comment by gosu821** [comment]
> mà giờ nó đã update sau vài phút nó check thì nó tự động tắt luôn :(( chắc downgrade xuống 4.198 quá

Chính xác thay vì change hwid hay rì thì nó vẫn nhận được

**Comment by Borisizdabezt** [comment]
yea

**Comment by gosu821** [comment]
Downgrade là ổn hơn rồi force không update trong file chính là được
Read only là 1 phép thử đơn giản

**Comment by gosu821** [comment]
Exitlag nó nhắm tới hwid thì rắc rối hơn nhiều, giờ tìm bản downgrade thôi

**Comment by Borisizdabezt** [comment]
để tôi downgrade xuống rồi tìm bug fix lại rồi up lên bản mới

**Comment by Borisizdabezt** [comment]
bản 4.198 không sao hết, không bị lỗi 0 day

**Comment by Borisizdabezt** [comment]
đợi 30 phút thử nếu nó tắt thì xem như là patched còn không tắt thì còn bug :))

**Comment by Borisizdabezt** [comment]
server side rồi
downgrade vẫn dính

**Comment by gosu821** [comment]
> server side rồi downgrade vẫn dính

client side thì có thể chứ serverside khó quớ

**Comment by Borisizdabezt** [comment]
tốt nhất là change hwid rồi restart rồi xài lại tool chứ biết sao nữa haiz
