### ISSUE TITLE
its work just now?

### ISSUE THREAD

**Issue by Makhronov** [Borisizdabezt/exitlag-trial-activator#4]
?

**Comment by MohamedWSalah** [comment]
it doesnt work for me, I tried it

**Comment by Borisizdabezt** [comment]
yea, it's patched

**Comment by Borisizdabezt** [comment]
Exitlag will check your hwid after 6-7 mins

**Comment by Borisizdabezt** [comment]
i think i will make a exitlag hwid spoofer

**Comment by Risejkee** [comment]
After 10 minutes of use, exitflag writes to me that "your account was logged in from another computer " ( something like that) and after this message throws it out of the account in 5 minutes

**Comment by Borisizdabezt** [comment]
https://github.com/Borisizdabezt/exitlag-hwid-spoofer
MOVE MOVE MOVE!
