### ISSUE TITLE
Hi, Sorry for disturbance but can you kindly add a readme file for how to use it step by step 

### ISSUE THREAD

**Issue by DevilsSoul** [Borisizdabezt/exitlag-trial-activator#5]
Sorry for disturbance but can you kindly add a readme file for how to use it step by step , i am not good with computer but i am working hard to learn , if you can kindly add the steps on a read me file , Thank You .

**Comment by Borisizdabezt** [comment]
ok if you want but it's patched

**Comment by DevilsSoul** [comment]
ok thank you , will you be able to crack to it ? or find a way to make it work ?

**Comment by Borisizdabezt** [comment]
i think i will cooperate with someone is good at C++ to create a HWID spoofer

**Comment by Borisizdabezt** [comment]
https://github.com/Borisizdabezt/exitlag-hwid-spoofer
MOVE MOVE MOVE!
