### ISSUE TITLE
i found a new way to pass it

### ISSUE THREAD

**Issue by Borisizdabezt** [Borisizdabezt/exitlag-trial-activator#7]
i need to wait for more 3 days (maybe) and i will public it, wait for it men :)
i have to go to school (6AM to 9PM lul asia education)

**Comment by w1tch666** [comment]
> i need to wait for more 3 days (maybe) and i will public it, wait for it men :) i have to go to school (6AM to 9PM lul asia education)

You're insane

**Comment by wizard460** [comment]
You're literally the best!!!

**Comment by ZeroTwoSimp420** [comment]
omg lets gooo you the best

**Comment by Borisizdabezt** [comment]
MOVE TO NEW REPOSITORY GUY! MOVE MOVE MOVE

**Comment by Borisizdabezt** [comment]
#8
